#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-libwww-perl
Version  : 6.15
Release  : 17
URL      : http://www.cpan.org/CPAN/authors/id/E/ET/ETHER/libwww-perl-6.15.tar.gz
Source0  : http://www.cpan.org/CPAN/authors/id/E/ET/ETHER/libwww-perl-6.15.tar.gz
Summary  : 'The World-Wide Web library for Perl'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0
Requires: perl-libwww-perl-bin
Requires: perl-libwww-perl-doc
BuildRequires : perl(Encode::Locale)
BuildRequires : perl(File::Listing)
BuildRequires : perl(HTML::Entities)
BuildRequires : perl(HTML::HeadParser)
BuildRequires : perl(HTTP::Cookies)
BuildRequires : perl(HTTP::Daemon)
BuildRequires : perl(HTTP::Date)
BuildRequires : perl(HTTP::Negotiate)
BuildRequires : perl(HTTP::Request)
BuildRequires : perl(HTTP::Request::Common)
BuildRequires : perl(HTTP::Response)
BuildRequires : perl(HTTP::Status)
BuildRequires : perl(LWP::MediaTypes)
BuildRequires : perl(Net::HTTP)
BuildRequires : perl(URI)
BuildRequires : perl(URI::Escape)
BuildRequires : perl(WWW::RobotRules)

%description
L I B W W W - P E R L - 6
-----------------------------
The libwww-perl collection is a set of Perl modules which provides a
simple and consistent application programming interface to the
World-Wide Web.  The main focus of the library is to provide classes
and functions that allow you to write WWW clients. The library also
contain modules that are of more general use and even classes that
help you implement simple HTTP servers.

%package bin
Summary: bin components for the perl-libwww-perl package.
Group: Binaries

%description bin
bin components for the perl-libwww-perl package.


%package doc
Summary: doc components for the perl-libwww-perl package.
Group: Documentation

%description doc
doc components for the perl-libwww-perl package.


%prep
%setup -q -n libwww-perl-6.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/LWP.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Authen/Basic.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Authen/Digest.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Authen/Ntlm.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/ConnCache.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Debug.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/DebugFile.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/MemberMixin.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/GHTTP.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/cpan.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/data.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/file.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/ftp.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/gopher.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/http.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/loopback.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/mailto.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/nntp.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Protocol/nogo.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/RobotUA.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/Simple.pm
/usr/lib/perl5/site_perl/5.26.1/LWP/UserAgent.pm
/usr/lib/perl5/site_perl/5.26.1/lwpcook.pod
/usr/lib/perl5/site_perl/5.26.1/lwptut.pod

%files bin
%defattr(-,root,root,-)
/usr/bin/lwp-download
/usr/bin/lwp-dump
/usr/bin/lwp-mirror
/usr/bin/lwp-request

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
